### ISSUE TITLE
Can't compile on Arduino IDE with ESP32 update v3.0.1

### ISSUE THREAD

**Issue by jmazzll** [pablo-sampaio/easy_mfrc522#4]
Hello 
I've noticed the examples can't compile with this update. 
Here is the error i get. 

c:\Users\xxxx\Documents\Arduino\libraries\MFRC522\src\MFRC522Extended.cpp: In member function 'MFRC522::StatusCode MFRC522Extended::TCL_Transceive(TagInfo*, byte*, byte, byte*, byte*)':
c:\Users\xxx\Documents\Arduino\libraries\MFRC522\src\MFRC522Extended.cpp:824:34: error: ordered comparison of pointer with integer zero ('byte*' {aka 'unsigned char*'} and 'int')
  824 |         if (backData && (backLen > 0)) {
      |                          ~~~~~~~~^~~
c:\Users\xxx\Documents\Arduino\libraries\MFRC522\src\MFRC522Extended.cpp:847:42: error: ordered comparison of pointer with integer zero ('byte*' {aka 'unsigned char*'} and 'int')
  847 |                 if (backData && (backLen > 0)) {
      |                                  ~~~~~~~~^~~

exit status 1

Compilation error: exit status 1
![Capture](https://github.com/pablo-sampaio/easy_mfrc522/assets/172935773/f5a9a2ac-2f3a-46c8-9809-1e04874148cd)

I went back on previous 2.0.17 version and it works again.

Thanks for your library !
